import { test, expect } from '@playwright/test';

for (const width of [1280, 390]) test(`description and reply draft stay local, survive reopening, and preserve shared status (${width}px)`, async ({ page }) => {
  const unexpected: string[] = [];
  await page.route('**/*', async route => {
    const request = route.request(); const url = new URL(request.url());
    if (['fetch', 'xhr'].includes(request.resourceType()) && (url.pathname.startsWith('/api/') || !['localhost', '127.0.0.1'].includes(url.hostname))) {
      unexpected.push(`${request.method()} ${url.origin}${url.pathname}`); await route.abort(); return;
    }
    await route.continue();
  });
  await page.setViewportSize({ width, height: width === 390 ? 844 : 1000 });
  await page.goto('/neo');
  if (width === 390 && await page.locator('aside').isVisible()) await page.getByRole('button', { name: 'Toggle sidebar', exact: true }).click();
  const secretary = page.getByRole('region', { name: 'Neo AI秘書' });
  await expect(secretary.getByText('ローカル検証用・架空データ。', { exact: false })).toBeVisible();
  await secretary.getByRole('button', { name: '整理', exact: true }).click();
  const proposal = secretary.getByRole('article', { name: '提案: 案内文を仕上げる', exact: true });
  await proposal.getByText('根拠・訂正・共有への反映', { exact: true }).click();
  await expect(proposal).toContainText('案内を公開し、申込を受け付けられるようにする。');
  await proposal.getByRole('button', { name: '説明をAIで編集', exact: true }).click();
  const chat = page.getByTestId('companion-ai-panel');
  await expect(chat.getByText('説明をどう直すか入力してください。')).toBeVisible();
  await chat.getByRole('textbox').fill('説明を「公開する案内文を確認する。」に変更して');
  await chat.getByRole('button', { name: '送信', exact: true }).click();
  await expect(chat.getByText('説明を変更しました。', { exact: true })).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await chat.getByRole('button', { name: '戻す', exact: true }).click();
  await expect(chat.getByText('変更を取り消しました。')).toBeVisible();
  await chat.getByRole('textbox').fill('説明を短く整理して');
  await chat.getByRole('button', { name: '送信', exact: true }).click();
  await chat.getByRole('button', { name: '変更前後を確認' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByText('変更前', { exact: true })).toBeVisible();
  await expect(dialog.getByText('変更後', { exact: true })).toBeVisible();
  await page.screenshot({ path: `test-results/taskflow-description-${width}.png`, fullPage: true, animations: 'disabled' });
  await dialog.getByRole('button', { name: '保存する', exact: true }).click();
  await expect(chat.getByText('説明を変更しました。', { exact: true })).toBeVisible();
  await page.reload();
  if (width === 390 && await page.locator('aside').isVisible()) await page.getByRole('button', { name: 'Toggle sidebar', exact: true }).click();
  if (!await chat.isVisible()) await page.getByTestId('companion-ai-toggle').click();
  await chat.getByRole('button', { name: '履歴', exact: true }).click();
  await chat.getByText('案内文を仕上げるの説明', { exact: true }).click();
  await expect(chat.getByText('説明を変更しました。', { exact: true })).toBeVisible();
  const history = chat.getByRole('region', { name: '会話履歴', exact: true });
  await expect(history).toBeVisible();
  await expect(history.getByRole('button', { name: '案内文を仕上げるの説明', exact: true })).toHaveAttribute('aria-current', 'true');
  await chat.getByRole('textbox').fill('まだ送らない下書き');
  const toggle = page.getByTestId('companion-ai-toggle');
  await expect(toggle).toBeVisible();
  await expect(toggle).toHaveAttribute('aria-expanded', 'true');
  const panelBox = await chat.boundingBox();
  const toggleBox = await toggle.boundingBox();
  expect(toggleBox!.y).toBeGreaterThan(panelBox!.y + panelBox!.height);
  await toggle.click();
  await expect(chat).toHaveCount(0);
  await toggle.click();
  await expect(history).toBeVisible();
  await expect(chat.getByRole('textbox')).toHaveValue('まだ送らない下書き');
  await page.keyboard.press('Escape');
  await secretary.getByRole('button', { name: '整理', exact: true }).click();
  await secretary.getByRole('button', { name: '返信案', exact: true }).click();
  await expect(chat.getByText('ご連絡ありがとうございます。紹介文を確認します。', { exact: false })).toBeVisible();
  await expect(chat.getByRole('link', { name: '元のメールを開く' })).toHaveAttribute('href', /mail.google.com/);
  await chat.getByRole('textbox').fill('返信案を短くして');
  await chat.getByRole('button', { name: '送信', exact: true }).click();
  await expect(chat.getByRole('button', { name: '本文をコピー', exact: true })).toHaveCount(2);
  await page.screenshot({ path: `test-results/taskflow-reply-${width}.png`, fullPage: true, animations: 'disabled' });
  await page.reload();
  if (width === 390 && await page.locator('aside').isVisible()) await page.getByRole('button', { name: 'Toggle sidebar', exact: true }).click();
  if (!await chat.isVisible()) await page.getByTestId('companion-ai-toggle').click();
  await chat.getByRole('button', { name: '履歴', exact: true }).click();
  await chat.getByText('紹介文の確認への返信案', { exact: true }).click();
  await expect(chat.getByRole('button', { name: '本文をコピー', exact: true })).toHaveCount(2);
  await expect(history).toBeVisible();
  await expect(toggle).toBeVisible();
  expect(await chat.evaluate(panel => panel.scrollWidth <= panel.clientWidth)).toBe(true);
  await page.screenshot({ path: `test-results/taskflow-history-${width}.png`, fullPage: true, animations: 'disabled' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect(unexpected).toEqual([]);
});
