import { beforeEach, expect, it, vi } from 'vitest';
const fake = vi.hoisted(() => ({ uid: 'alice', mock: false, exists: vi.fn(), readMock: vi.fn() }));
vi.mock('@/stores/authStore', () => ({ useAuthStore: { getState: () => ({ user: { id: fake.uid } }) } }));
vi.mock('@/lib/firebase/testMode', () => ({ isE2EMockAuthEnabled: () => fake.mock }));
vi.mock('@/lib/firebase/firestore', () => ({ taskHasComments: fake.exists }));
vi.mock('@/lib/task/detailMock', () => ({ readTaskDetailsMock: fake.readMock }));
import { ensureTaskCommentPresence, failTaskCommentPresence, publishTaskCommentPresence, publishTaskCommentSnapshot, taskCommentPresenceKey, useTaskCommentPresenceStore } from './taskPresence';
const scope = { userId: 'alice', projectId: 'project', taskId: 'task' };
const entry = (target = scope) => useTaskCommentPresenceStore.getState().entries[taskCommentPresenceKey(target)];
beforeEach(() => {
  vi.resetAllMocks(); fake.uid = 'alice'; fake.mock = false;
  useTaskCommentPresenceStore.setState({ entries: {} });
  fake.exists.mockResolvedValue(false);
});
it('deduplicates in-flight visible reads and reuses the result within its cache lifetime', async () => {
  let resolve!: (value: boolean) => void;
  fake.exists.mockReturnValue(new Promise(done => { resolve = done; }));
  const one = ensureTaskCommentPresence(scope);
  const two = ensureTaskCommentPresence(scope);
  expect(one).toBe(two); expect(fake.exists).toHaveBeenCalledTimes(1);
  expect(entry()?.status).toBe('loading');
  resolve(true); await one;
  expect(entry()).toMatchObject({ status: 'ready', hasComments: true });
  await ensureTaskCommentPresence(scope); expect(fake.exists).toHaveBeenCalledTimes(1);
  const old = entry()!;
  useTaskCommentPresenceStore.setState({ entries: { [taskCommentPresenceKey(scope)]: { ...old, checkedAt: Date.now() - 60_001 } } });
  await ensureTaskCommentPresence(scope); expect(fake.exists).toHaveBeenCalledTimes(2);
});
it('keeps failed reads unknown and retries without pretending there are zero comments', async () => {
  fake.exists.mockRejectedValueOnce(new Error('permission'));
  await ensureTaskCommentPresence(scope);
  expect(entry()).toMatchObject({ status: 'error' }); expect(entry()).not.toHaveProperty('hasComments');
  await ensureTaskCommentPresence(scope);
  expect(entry()).toMatchObject({ status: 'ready', hasComments: false });
});
it('does not let an older request overwrite a newer detail snapshot or another account', async () => {
  let resolve!: (value: boolean) => void;
  fake.exists.mockReturnValueOnce(new Promise(done => { resolve = done; }));
  const read = ensureTaskCommentPresence(scope);
  publishTaskCommentPresence(scope, true);
  resolve(false); await read;
  expect(entry()).toMatchObject({ status: 'ready', hasComments: true });
  const otherTask = { ...scope, taskId: 'other' };
  fake.exists.mockReturnValueOnce(new Promise(done => { resolve = done; }));
  const pending = ensureTaskCommentPresence(otherTask);
  fake.uid = 'bob'; resolve(true); await pending;
  expect(entry(otherTask)?.status).not.toBe('ready');
  const bob = { ...scope, userId: 'bob' };
  expect(entry(bob)).toBeUndefined();
  await ensureTaskCommentPresence(bob);
  expect(entry(bob)).toMatchObject({ status: 'ready', hasComments: false });
});
it('limits simultaneous reads to three and uses no Firebase request in mock mode', async () => {
  const resolvers: ((value: boolean) => void)[] = [];
  fake.exists.mockImplementation(() => new Promise(done => { resolvers.push(done); }));
  const reads = Array.from({ length: 5 }, (_, n) => ensureTaskCommentPresence({ ...scope, taskId: `task-${n}` }));
  expect(fake.exists).toHaveBeenCalledTimes(3);
  resolvers.slice(0, 3).forEach(resolve => resolve(false));
  await Promise.all(reads.slice(0, 3)); await Promise.resolve();
  expect(fake.exists).toHaveBeenCalledTimes(5);
  resolvers.slice(3).forEach(resolve => resolve(true)); await Promise.all(reads);
  fake.mock = true; fake.readMock.mockReturnValue({ comments: [{ id: 'sample-comment' }] });
  await ensureTaskCommentPresence(scope);
  expect(entry()).toMatchObject({ status: 'ready', hasComments: true });
  expect(fake.readMock).toHaveBeenCalledWith('project', 'task');
  expect(fake.exists).toHaveBeenCalledTimes(5);
});
it('ignores cache-only empty snapshots and verifies empty ordered snapshots before removing a mark', async () => {
  publishTaskCommentPresence(scope, true);
  publishTaskCommentSnapshot(scope, 0, true);
  expect(entry()).toMatchObject({ status: 'ready', hasComments: true }); expect(fake.exists).not.toHaveBeenCalled();
  publishTaskCommentSnapshot(scope, 0, false);
  await ensureTaskCommentPresence(scope);
  expect(entry()).toMatchObject({ status: 'ready', hasComments: false });
  publishTaskCommentSnapshot(scope, 1, false);
  expect(entry()).toMatchObject({ status: 'ready', hasComments: true });
  failTaskCommentPresence(scope);
  expect(entry()?.status).toBe('error');
});
